# Generated by Django 5.0.6 on 2025-02-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='rank',
            field=models.CharField(default='', max_length=100),
        ),
    ]
